<a href="https://colab.research.google.com/github/joaquinmenendez/curso_phyton/blob/master/Propuesta_curso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Exploración y visualización de datos en Python
Docentes a cargo: [Joaquín Menéndez](https://www.linkedin.com/in/joaquin-menendez/)

Tanto este curso como el curso `Introducción a Python para ciencia de datos e IA` pueden accederse en el siguiente repositorio [JIS-2020](https://github.com/joaquinmenendez/JIS-2020)

## Temas

1. Introducción a Numpy y Pandas
    - `array`, matrices, `Series` y `DataFrames`
    - Leer archivos  
    - Interactuar con nuestro dataset (indexing, filtering, merge)
2. Análisis Exploratorio de Datos
    - Análisis descriptivo (none values, media, percentiles, outliers) 
    - Plotear los graficos mas comunes (barras, boxplot, lineplot, matrix de correlaciones) 
4. Introducción a la Estadística inferencial
    - Evaluar normalidad de nuestros datos
    - Comparar Hipotesis
    - Regresion Lineal usando `statsmodels`

## Links útiles
- [Anaconda](https://www.anaconda.com/products/individual)
- [Google Colab](https://colab.research.google.com/)
- [2 meses grátis de Datacamp](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-datacamp)
- [StackOverflow](https://stackoverflow.com/)
- [Python (documentación)](https://python-reference.readthedocs.io/en/latest/index.html#)
- [Slicing](https://python-reference.readthedocs.io/en/latest/docs/brackets/slicing.html)



# ¿Qué es el Análisis Exploratorio de Datos?

Hemos visto en el primer curso algo de Pandas y sus diferentes funciones. En este módulo, indagaremos más acerca de cómo usarlo para realizar un 'Analisis Exploratorio de los Datos' o `EDA` (en ingles, 'Exploratory Data Analysis'). El EDA es un paso previo e imprescindible a la hora de comprender los datos con los que se va a trabajar y altamente recomendable para una correcta metodología de investigación.

El objetivo de este análisis es explorar, describir, resumir y visualizar la naturaleza de los datos recogidos en las variables del proyecto o investigación de interés, mediante la aplicación de técnicas simples de resumen de datos y métodos gráficos sin asumir asunciones para su interpretación. Luego de la `Adquisicion` de los datos, el `EDA` es el tercer paso en todo proyecto de Analisis de Datos. <br>

![Ciclo de vida de los datos](https://www.eduliticas.com/wp-content/uploads/2017/05/pasos-clave-ciclo-analitico.png)

Podemos decir de una manera general que los pasos en la exploración y preprocesamiento de datos son:
1. Identificación de variables y tipos de datos
2. Analizando las métricas básicas
3. Análisis univariante no gráfico
4. Análisis gráfico univariado
5. Análisis bivariado
6. Transformaciones variables
7. Tratamiento de valor perdido
8. Tratamiento de valores atípicos
9. Análisis de correlación
10. Reducción de dimensionalidad

En este curso no vamos a ver en profundidad los puntos `[7,8,10]` dado que ameritan un curso en si mismos y usualmente son herramientas o pasos mas orientados a la creación de modelos estadísticos o de Machine Learning.

## 1. Introducción a Numpy y Pandas

Antes de empezar con el EDA propiamente repasamos las dos principales librerías que usaremos.

### Numpy
**Arrays y Matrices**

La programación gráfica se fundamenta sobre la idea de manipular información almacenada en unas estructuras conocidas como vectores y matrices. En Python (nativo) la única forma de simular estas estructuras es usando listas y lo malo es que son muy limitadas respecto a las funciones matemáticas que permiten. Numpy viene a solucionar esa carencia ofreciéndonos un nuevo tipo de dato llamado array.

Un array es parecido a una lista en Python y de hecho se pueden crear a partir de ellas:

In [21]:
import numpy as np 
from IPython import display
# Vamos a importa la libreria Numpy y vamos a abreviarla para no escribir tanto en el futuro

In [2]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [3]:
# Propiedades importantes de los arrays
print( 'Dimensiones:', array.shape)
print( 'Tipo de datos:', array.dtype)

Dimensiones: (5,)
Tipo de datos: int64


In [4]:
# Funciones que operan sobre los arrays
print( 'Valor Mínimo', array.min())
print( 'Valor Máximo', array.max())
print( 'Media', array.mean())
print( 'Desvío Standard', array.std())
print( 'Indice que contiene el valor máximo', array.argmax())


Valor Mínimo 1
Valor Máximo 5
Media 3.0
Desvío Standard 1.4142135623730951
Indice que contiene el valor máximo 4


In [5]:
array2 = np.array([1,2,3, "cuatro"])
array2.dtype

dtype('<U21')

In [6]:
array2.mean()

TypeError: cannot perform reduce with flexible type

Si bien es posible incluir mas de un tipo de data en un Array, esto nos va a impedir realizar ciertas operaciones. Esto es importante para cuando trabajemos con columnas.


**Indexing**

Al igual que en las listas, vamos a poder indexar o "llamar"a un o varios elementos de nuestro array.
La siguiente imagen muestra como "Seleccionabamos" elementos de una lista.<br>
![Slicing](https://user-images.githubusercontent.com/43391630/94975818-dc4ab100-04e0-11eb-85ab-b58939445f1b.png)

Ahora bien, en el caso de los arrays veremos que tenemos una pequeña diferencia. Estos pueden tener la forma de una lista, pero pueden tener dos dimensiones (filas y columnas), hasta las N dimensiones que queramos.<br>
![Indexing](https://user-images.githubusercontent.com/43391630/94975755-a3aad780-04e0-11eb-8eab-37d8e205a888.png)

In [22]:
# Ejemplo de como indexar un array de una dimension
var = np.array([1,2,3,4,5])
var[0], var[-1]

(1, 5)

In [23]:
#Como mencionamos anteriormente un array puede tener mas de una diemnsión
matrix_var = np.array([
                       [1,2,3],
                       [4,5,6],
                       [7,8,9]
])
print("Dimensión:", matrix_var.shape)
matrix_var

Dimensión: (3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
matrix_var[0]

array([1, 2, 3])

In [25]:
matrix_var[1,-1]  # Primer elementos las filas, segundo elemento las columnas

6

In [26]:
matrix_var[:,1:] # Dame de todas las filas, los valores de la segunda columna hasta la ultima columna

array([[2, 3],
       [5, 6],
       [8, 9]])

Para mas informacion de como usar los indices para seleccionar datos, consultar la [documentacion](https://numpy.org/doc/stable/reference/arrays.indexing.html) de Numpy.

**Operaciones** 

Otra de las ventajas de numpy es que nos permite realizar operaciones entre arrays y escalares y arrays y otros arrays.

In [27]:
# Sumar un escalar a todos los elementos de un array
np.array([1,2,3]) + 3

array([4, 5, 6])

In [28]:
# Sumar un array con otro array
np.array([1,2,3,4,5]) + np.array([9,9,9,9,9])

array([10, 11, 12, 13, 14])

Cuando realicemos operaciones entre arrays es importante que ambos tengan las mismas dimensiones, sino Numpy no sabra como operar y tendremos un errror como el siguiente:

In [29]:
np.array([1,2,3,4,5]) + np.array([9,5])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [30]:
# Restas
np.array([1,2,3,4,5]) - np.array([9,9,9,9,9])

array([-8, -7, -6, -5, -4])

In [31]:
# Multiplicar un array o vector por un escalar
np.array([1,2,3,4,5]) * 2

array([ 2,  4,  6,  8, 10])

In [34]:
# Las mismas operaciones pueden realizarse con arrays de mas dimensiones, o comunmente denominados matrices
display.display(matrix_var)
matrix_var * 2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [18]:
matrix_var * matrix_var # Multiplicacion pair-wise

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [19]:
matrix_var @ np.array([1,1,1]) # Multiplicacion de matrices

array([ 6, 15, 24])

Para mas informacion acerca de las principales operaciones algebraicas utilizando Numpy consultar este [link](https://cmdlinetips.com/2019/06/9-basic-linear-algebra-operations-with-numpy/)

### Pandas

Pandas es una de las librerías de Python más usadas para análisis de datos. El nombre pandas viene de "Panel Data Analysis" y su funcionalidad permite hacer operaciones sobre datos que se encuentran en memoria de manera eficiente.

Pandas es útil para trabajar sobre datos tabulares, con dos condiciones importantes:

    I. Los datos se encuentran enteramente en la memoria RAM. Con lo cual, el tamaño de los datos que podemos manipular está limitado por el hardware. Como regla de pulgar, es una buena práctica no ocupar más de 1/3 de la memoria RAM de nuestro dispositivo con el dataset.

    II. En pandas, las operaciones sobre filas y columnas son, en general, eficientes porque se hacen de forma "vectorizada". En realidad esta optimización, se hace desde numpy, una librería para realizar operaciones matemáticas que se utilizó a su vez para escribir pandas.

In [36]:
import pandas as pd  #Importamos la libreria

**Series**

In [37]:
# Series
serie = pd.Series(data = [1,2,2,3,4,5,5,5,5])
serie

0    1
1    2
2    2
3    3
4    4
5    5
6    5
7    5
8    5
dtype: int64

In [39]:
# Propiedades importantes de las series
print('Tipo de objetos que tiene:', serie.dtype)
print('Nombre:', serie.name)
print('Index:',serie.index)
print('Valores:',serie.values)

Tipo de objetos que tiene: int64
Nombre: None
Index: RangeIndex(start=0, stop=9, step=1)
Valores: [1 2 2 3 4 5 5 5 5]


In [40]:
serie.min()

1

In [41]:
serie.max()

5

In [42]:
serie.idxmax()  # Devuelve el indice donde se encuentra el maximo valor de mi serie.

5

In [43]:
serie[serie.idxmax()]

5

In [44]:
## Funciones que operan sobre los arrays
# Similares a las que usamos anteriomente con nuestros arrays. Esto no es una sorpresa dado que Pandas esta montado sobre Numpy
print('Media',serie.mean())
print('Mediana',serie.median())
print('Moda', serie.mode().values)
print('Desvio Standard',serie.std())

Media 3.5555555555555554
Mediana 4.0
Moda [5]
Desvio Standard 1.5898986690282426


Al mismo tiempo podemos aplicar metodos propios de las Series

In [ ]:
serie.astype(str).mean()  #Podemos pedir el valor promedio pero no va a tener ningun sentido para nosotros

In [ ]:
serie.count()

In [ ]:
serie.unique()

In [ ]:
serie.nunique()

**Masking**

Llamamos `masking`cuando sometemos a un `array` o una `Series` a una evaluación lógica, para filtrar los datos que coincidan con dicha evaluación. Una mascara es un array de booleanos, con  True en los valores que cumplen la condición y False donde no. Una vez que creamos la máscara, podemos usarla para seleccionar de nuestro arreglo aquellos elementos que queremos filtrar.




In [45]:
mask = serie > 4
mask

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [ ]:
serie[mask] # Solo debería seleccionar los valores mayores a 4

**Dataframes**

In [46]:
## DataFrame
df = pd.DataFrame(data = {'columna1' : [1,2,3],
                          'columna2' : ["uno", "dos", "tres"]
                         })
df

columna1 columna2
0         1      uno
1         2      dos
2         3     tres

In [48]:
# Propiedades importantes de los dataframes
print('Columnas: ', df.columns)
print('Index: ', df.index)
print('Dimensiones: ',df.shape)

Columnas:  Index(['columna1', 'columna2'], dtype='object')
Index:  RangeIndex(start=0, stop=3, step=1)
Dimensiones:  (3, 2)


In [49]:
df.describe() #Nuevamente vemos que el typo de data nos va a permitir ciertas operaciones

columna1
count       3.0
mean        2.0
std         1.0
min         1.0
25%         1.5
50%         2.0
75%         2.5
max         3.0

In [50]:
df.dtypes

columna1     int64
columna2    object
dtype: object

In [51]:
df.info() # si queremos tener un pantallazo mas completo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   columna1  3 non-null      int64 
 1   columna2  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


### Actividad práctica
Pandas puede crear dataframes si les pasamos una URL. 
Proba de ver el siguiente dataset: https://raw.githubusercontent.com/joaquinmenendez/JIS-2020/main/data/admision_universidad.csv

La idea es que cargues este dataset y uses el método describe para ver un pantallazo rápido de los datos.
Pandas te permite leer archivos usando los métodos `.read_...`. Fijate cuál es la extensión del archivo y eso te dará una pista de que método usar.
- Queremos saber cual es la mediana para el GPA
- Vamos a usar un filtro para hacer dos grupos unos con un GPA < a la mediana y otro con un GPA >=
- Para cada una de estas grupos vamos a calcular la media del GMAT.


## 2. Exploracion y Análisis de datos

Podemos decir de una manera general que los pasos en la exploración y preprocesamiento de datos son:
1. Identificación de variables y tipos de datos
2. Analizando las métricas básicas
3. Análisis univariante no gráfico
4. Análisis gráfico univariado
5. Análisis bivariado
6. Transformaciones de variables
7. Tratamiento de valor perdido
8. Tratamiento de valores atípicos
9. Análisis de correlación
10. Reducción de dimensionalidad

En este curso no vamos a ver en profundidad los puntos `[7,8,10]` dado que ameritan un curso en si mismos y usualmente son herramientas o pasos mas orientados a la creación de modelos estadísticos o de Machine Learning.

Vamos a descargar un dataset con datos mas similares a la vida real.<br>
Este conjunto de datos contiene información sobre bebés recién nacidos y sus padres. Contiene principalmente variables continuas (aunque algunas tienen solo unos pocos valores, por ejemplo, el número de cigarrillos fumados por día) y es más útil para la correlación y regresión. El peso al nacer de los bebés que las madres fumaron se ha ajustado ligeramente para exagerar las diferencias entre las madres que fumaban y las que no fumaban.<br>
Puedes encontrar mas información de este dataset [aquí](https://rdrr.io/cran/UsingR/man/babies.html).


In [59]:
import pandas as pd

In [60]:
df = pd.read_csv('./data/babiesdata.csv')  # Leo un archivo en mi filesystem
df.head(5)  # Mostrame las primeras 5 filas

id  date  gestation  bwt/oz  parity  mrace  mage  med   mht  mpregwt  \
0  6114  1404      269.0     115       2    6.0  30.0  2.0  62.0    115.0   
1  3558  1631      269.0      90       4    0.0  26.0  2.0  67.0    125.0   
2  7570  1420      274.0     108       3    7.0  28.0  1.0  66.0    175.0   
3  4396  1631      274.0     130       4    7.0  26.0  3.0  64.0    185.0   
4  4401  1606      275.0     106       3    4.0  31.0  4.0  65.0    142.0   

   ...  dage  ded   dht    dwt  marital  inc  smoke  time  number  Premature  
0  ...  29.0  1.0  67.0  130.0        1  1.0    NaN   NaN     NaN        1.0  
1  ...  27.0  5.0  75.0  220.0        1  8.0    NaN   NaN     NaN        1.0  
2  ...  36.0  4.0   NaN    NaN        1  1.0    NaN   NaN     NaN        0.0  
3  ...  26.0  2.0  74.0  225.0        1  3.0    NaN   NaN     NaN        0.0  
4  ...  38.0  5.0  69.0  212.0        1  8.0    NaN   NaN     NaN        0.0  

[5 rows x 21 columns]

### 1. Identificación de variables y tipos de datos

In [61]:
df.shape

(1038, 21)

In [62]:
df.dtypes

id             int64
date           int64
gestation    float64
bwt/oz         int64
parity         int64
mrace        float64
mage         float64
med          float64
mht          float64
mpregwt      float64
drace        float64
dage         float64
ded          float64
dht          float64
dwt          float64
marital        int64
inc          float64
smoke        float64
time         float64
number       float64
Premature    float64
dtype: object

In [63]:
# Verificar si hay datos faltantes
df.isna().sum()

id             0
date           0
gestation     10
bwt/oz         0
parity         0
mrace          1
mage           1
med            1
mht           20
mpregwt       32
drace          4
dage           5
ded           12
dht          425
dwt          430
marital        0
inc          106
smoke         10
time          10
number        10
Premature     10
dtype: int64

In [ ]:
round(df.isna().sum() / df.shape[0] * 100, 2)

Ojo! Miramos el porcentaje de datos faltante del padre. Esto nos puede dar cuenta de que el padre no estaba presente al momento de la evaluación o quizas que no estuvo presente durante el embarazo.

**Removiendo valores faltantes**

In [ ]:
df_notna = df.copy()
df_notna = df_notna.dropna()

Notaras que usamos un comando llamado `copy`, lo que hace es otorgarnos una copia de los valores, en vez de el mismo objeto. Esto es un tema un poco complejo, pero la explicación breve es que cuando asignamos valores a una variable Python los guarda de manera diferenciada. Por una parte tenemos el nombre de la variable, y por otro el contenido. En vez de duplicar los datos, python asigna `punteros` señalando donde estan los datos. Esto es comodo ya que Python hace todo el trabajo, pero si hacemos modificaciones en nuestros datos, esto repercutira en todas las variables que apuntaban a los mismos. Una discusión acerca de este tema puede encontrarse [aquí](https://es.stackoverflow.com/questions/397/entendiendo-la-ausencia-de-punteros-en-python)

**Removiendo columnas que no son de nuestro interes**

In [ ]:
df_notna.drop(columns=["drace","dage","ded","dht","dwt","marital","inc"])

In [ ]:
df_notna.drop(columns=["drace","dage","ded","dht","dwt","marital","inc"], inplace = True)

El argumento `inplace` opera sobre nuestro DataFrame evitando la necesidad de asignar el DF modificado a una nueva variable. **Usar con precaución!!**

<p style="background-color:red; text-align:center">Descargando un nuevo dataset</p>

Pandas me permite leer el archivo directamente desde una URL si así lo quisieras.
Si el usuario lo desea puede acceder a un dataset mas acotado y ya limpio en el siguiente [enlace](https://www.sheffield.ac.uk/mash/statistics/datasets).

Vamos a usar ese para simular que ya elegimos las variables que nos resultaron interesantes y ya limpiamos los datos. En nuestro caso vamos a centrarnos exclusivamente en variables relacionadas a la madre.

In [64]:
df = pd.read_csv('https://www.sheffield.ac.uk/polopoly_fs/1.886038!/file/Birthweight_reduced_R.csv')
df.head()

id  headcirumference  length  Birthweight  Gestation  smoker  motherage  \
0  1313                12      17          5.8         33       0         24   
1   431                12      19          4.2         33       1         20   
2   808                13      19          6.4         34       0         26   
3   300                12      18          4.5         35       1         41   
4   516                13      18          5.8         35       1         20   

   mnocig  mheight  mppwt  fage  fedyrs  fnocig  fheight  lowbwt  mage35  \
0       0       58     99    26      16       0       66       1       0   
1       7       63    109    20      10      35       71       1       0   
2       0       65    140    25      12      25       69       0       0   
3       7       65    125    37      14      25       68       1       1   
4      35       67    125    23      12      50       73       1       0   

  LowBirthWeight  
0            Low  
1            Low  
2         Normal  
3            Low  
4            Low

In [65]:
df.shape

(42, 17)

In [66]:
df.dtypes

id                    int64
headcirumference      int64
length                int64
Birthweight         float64
Gestation             int64
smoker                int64
motherage             int64
mnocig                int64
mheight               int64
mppwt                 int64
fage                  int64
fedyrs                int64
fnocig                int64
fheight               int64
lowbwt                int64
mage35                int64
LowBirthWeight       object
dtype: object

In [67]:
# Verificar si hay datos faltantes
df.isna().sum()

id                  0
headcirumference    0
length              0
Birthweight         0
Gestation           0
smoker              0
motherage           0
mnocig              0
mheight             0
mppwt               0
fage                0
fedyrs              0
fnocig              0
fheight             0
lowbwt              0
mage35              0
LowBirthWeight      0
dtype: int64

### 2. Analizando las métricas básicas

In [68]:
round(df.describe(),2)

id  headcirumference  length  Birthweight  Gestation  smoker  \
count    42.00             42.00   42.00        42.00      42.00   42.00   
mean    894.07             13.26   19.93         7.26      39.19    0.52   
std     467.62              0.77    1.11         1.33       2.64    0.51   
min      27.00             12.00   17.00         4.20      33.00    0.00   
25%     537.25             13.00   19.00         6.45      38.00    0.00   
50%     821.00             13.00   20.00         7.25      39.50    1.00   
75%    1269.50             14.00   21.00         8.00      41.00    1.00   
max    1764.00             15.00   22.00        10.00      45.00    1.00   

       motherage  mnocig  mheight   mppwt   fage  fedyrs  fnocig  fheight  \
count      42.00   42.00    42.00   42.00  42.00   42.00   42.00    42.00   
mean       25.55    9.43    64.40  125.86  28.90   13.67   17.19    70.76   
std         5.67   12.51     2.55   15.88   6.86    2.16   17.31     2.84   
min        18.00    0.00    58.00   99.00  19.00   10.00    0.00    66.00   
25%        20.25    0.00    63.00  115.00  23.00   12.00    0.00    69.00   
50%        24.00    4.50    64.00  125.00  29.50   14.00   18.50    71.00   
75%        29.00   15.75    66.00  135.00  32.00   16.00   25.00    72.00   
max        41.00   50.00    71.00  170.00  46.00   16.00   50.00    78.00   

       lowbwt  mage35  
count   42.00    42.0  
mean     0.14     0.1  
std      0.35     0.3  
min      0.00     0.0  
25%      0.00     0.0  
50%      0.00     0.0  
75%      0.00     0.0  
max      1.00     1.0

`describe` solo muestra las columnas cuyo tipo es númerico. En este caso, la información que se nos brinda es es solo de las variables que son númericas, otro tipo de variables pierden su significado al intentar asignarles métricas por lo cual no son tenidas en cuenta.

Algunos elementos que si nos llaman la atención:
- smoker : Mother smokes
```text
    1 = smoker 
    0 = non-smoker
```
- lowbwt : Low birth weight
```text
    1 = No
    0 = Yes
```
- mage35 : Mother over 35
```text
    1 = No 
    0 = Yes
```

### 3.	Análisis univariante (no gráfico)

**Contar casos**

Cuando observamos as columnas que no fueron descriptas usando el metodo `decribe` notamos algunas que pueden sernos de interes a la hora de construir un modelo.

In [69]:
df.LowBirthWeight.value_counts()

Normal    36
Low        6
Name: LowBirthWeight, dtype: int64

In [70]:
df.LowBirthWeight.value_counts() / df.shape[0] 

Normal    0.857143
Low       0.142857
Name: LowBirthWeight, dtype: float64

Al mismo tiempo nos puede interesar contar cuantos casos tenemos para nuestras variables dicotómicas (binarias)

In [71]:
binarias = ["smoker", "lowbwt","mage35"]

In [80]:
for col in binarias:
    print(round(df[col].value_counts(normalize = True) * 100, 2))

1    52.38
0    47.62
Name: smoker, dtype: float64
0    85.71
1    14.29
Name: lowbwt, dtype: float64
0    90.48
1     9.52
Name: mage35, dtype: float64


**Filtrando según una condición**

In [81]:
df[df.smoker == 1].shape

(22, 17)

In [82]:
df[(df.smoker == 1) & (df.lowbwt == 1)].shape

(5, 17)

Que pasa si por ejemplo nos interesaria ver estadisticos descriptivos o contar casos de una variable en relación a otra?

Esto es muy similar a como usamos las tablas Pivot en Excel.<br>
La función de `DataFrame.pivot_table` permite crear una tabla dinámica fácilmente, eligiendo qué columnas se quieren mostrar en:

- **índice** (index): la variable elegida para organizar los casos en filas.
- **columnas** (columns): lla variable elegida para organizar los casos en columnas.
- **valores** (values): las variables que se quieren observar dependiendo de los valores de las filas y columnas.

Y se puede elegir una o más funciones de agregación para aplicar a los valores cuando son agregados.

In [89]:
df.pivot_table(
    index=['smoker'],
    columns = ['LowBirthWeight'],
    values=['Birthweight'],
#   aggfunc='median',
#   margins = True,
#   margins_name='Medias totales'
)

Birthweight                      
LowBirthWeight         Low Normal Medias totales
smoker                                          
0                     5.80    7.5           7.40
1                     5.20    7.3           7.00
Medias totales        5.35    7.4           7.25

In [96]:
df.pivot_table(
    index=['mage35', "smoker"],
    values=['Birthweight'],
    aggfunc='median',
    margins = True,
    margins_name='Media total'
)

Birthweight
mage35      smoker             
0           0              7.30
            1              7.00
1           0              9.00
            1              6.00
Media total                7.25

Pandas nos permite realizar analisis para grupos escpicificos. En otras palabras, nos permite segmentar nuestro dataset en X grupos, donde X corresponde con los niveles de una o varias varibles. Ejemplo:

In [103]:
df.groupby(by=['smoker', 'mage35']).count()

id  headcirumference  length  Birthweight  Gestation  \
smoker mage35                                                         
0      0       19                19      19           19         19   
       1        1                 1       1            1          1   
1      0       19                19      19           19         19   
       1        3                 3       3            3          3   

               motherage  mnocig  mheight  mppwt  fage  fedyrs  fnocig  \
smoker mage35                                                            
0      0              19      19       19     19    19      19      19   
       1               1       1        1      1     1       1       1   
1      0              19      19       19     19    19      19      19   
       1               3       3        3      3     3       3       3   

               fheight  lowbwt  LowBirthWeight  
smoker mage35                                   
0      0            19      19              19  
       1             1       1               1  
1      0            19      19              19  
       1             3       3               3

In [105]:
df.groupby(by=['LowBirthWeight', 'smoker']).count()['id']

LowBirthWeight  smoker
Low             0          1
                1          5
Normal          0         19
                1         17
Name: id, dtype: int64

In [106]:
df.groupby(by=['LowBirthWeight', 'smoker'])['Gestation'].agg('median')

LowBirthWeight  smoker
Low             0         33
                1         35
Normal          0         40
                1         40
Name: Gestation, dtype: int64

### Actividad práctica
Para la siguiente actividad vamos a usar el dataset del Titanic ([link](https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/problem12.html)). 
Usa el link en la página para descargar el dataset y veamos:
- Si hay datos faltantes
- Cuantos gente sobrevivio 
- El promedio ('mean') del precio pagado por el ticket según si sobrevivieron o no.

### 4.	Análisis gráfico univariado

#### Matplotlib

Python ofrece una gran cantidad de librerias externas (es decir que las puede instalar usando `pip install`) para plotear datos. Dentro de las mas destacadas se encuentran [Seaborn](https://seaborn.pydata.org/), [Bokeh](https://docs.bokeh.org/en/latest/index.html), [Plotly](https://plotly.com/), entre otras. Sin embargo, Python ofrece una libreria por defecto llamada `matplotlib` que es muy versatil y siempre es una buena primera opción al momento de hacer nuestros primeros ploteos exploratorios.
Por ejemplo, el gráfico que acabamos de realizar fue hecho tambien con `matplotlib`, Pandas lo usa por defecto en su función `plot()`.

Exploremos un poco esta libreria:

In [ ]:
import  matplotlib.pyplot as plt
plt.plot(np.array([1,2,3,4]),
         np.array([3,3,4,3]))

Pasan varias cosas aquí.
Primero observamos una leyenda que dice `[<matplotlib.lines.Line2D at ...>]`. Por qué sucede esto? Porque por defecto `plot()` produce un objeto gráfico.
El usuario posee una gran capacidad para customizar estos gráficos y agregar detalles. Es aquí donde tanta flexibilidad puede volverse medio incomodo, ya que debemos recordar el nombre de todos los diferentes argumentos que queremos modificar. Una lista de estos puede consultarse [aquí](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.html) y [aquí](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.plot.html?highlight=matplotlib%20pyplot%20plot#matplotlib.pyplot.plot).

#### Histograma
En estadística, un histograma es una representación gráfica de una variable en forma de barras, donde la superficie de cada barra es proporcional a la frecuencia de los valores representados. Link a la [documentación](https://matplotlib.org/3.3.1/api/_as_gen/matplotlib.pyplot.hist.html) de matplotlib

In [ ]:
plt.hist(df.motherage)

Pandas va a utilizar Marplotlib para plotear los valores de cada columna. 

In [ ]:
df.motherage.plot(kind='hist')

Si bien Pandas nos va a permitir realizar ciertos gráficos sobre nuestras columnas, vamos a ver como podemos hacer todo esto directamente usando `matplotlib`. Esto nos va a permitir mucha flexibilidad. A su vez, no siempre vamos a plotear datos provenientes de un dataframe por lo cual es importante aprender como hacer esto.

In [ ]:
plt.hist(df.motherage, edgecolor = 'black')
plt.xlabel('Edad'), plt.ylabel('Frecuencia')
plt.title('Frecuencia de edad de la madre')
plt.show()

`matplotlib` nos va a permitir plotear diferentes datos en un mismo par de ejes x,y. Para esto creamos un par de ejes iniciales, en este caso lo haremos directamente con la función `plot.hist()`. Luego plotearemos un nuevo grafico con nueva información sobre etos mismos ejes.
Vamos a hacer dos histogramas, uno con los distribución de edad para Fumadores y otro para no Fumadores.

In [ ]:
#Fuman
plt.hist(df[df.smoker == 1].motherage, 
         color = 'red',
         edgecolor = 'k',
         #histtype='step',
         label= 'Fumador',
         alpha = 0.4
        )
#Nofuman
plt.hist(df[df.smoker == 0].motherage, 
         color = 'blue',
         edgecolor = 'k',
         #histtype='step',
         label= 'No Fumador',
         alpha = 0.4
        )

Vemos que ambos gráficos comparten los mismos ejes. Sin embargo, vemos que en este caso los 'bins' difieren en su localización lo cual vuelven la comparación un poco más difícil.
A su vez vemos que la función `plot.hist()` devielve tres elementos antes de devolver el objeto gráfico. Estos son la frecuencia para cada bin, las coordenadas en el eje X de los bins, y los poligonos o barras.

In [ ]:
plt.figure(figsize=(8,5)) # creamos una figura, la vamos a hacer mas grande.
valores, ticks , polygon = plt.hist(df[df.smoker == 1].motherage, 
                                     range= (16,46), # Seteamos el rango de datos que vamos a mostrar
                                     bins = 10,  # Seteamos la cantidad de bins
                                     edgecolor = 'red',
                                     color = 'red',
                                     label= 'Fumador',
                                     alpha = 0.4
                                    )
plt.hist(df[df.smoker == 0].motherage,
         range= (16,46),
         bins = 10,
         edgecolor = 'blue',
         color = 'blue',
         #histtype='step',
         label= 'No fumador',
         alpha = 0.4,
        )

plt.xlabel('Edad'), plt.ylabel('Frecuencia') # Nombramos nuestros ejes
plt.xticks(ticks=ticks) # seteamos que los ticks sean los del primer grafico
plt.legend()
plt.show()

#### Boxplot
Los diagramas de Caja-Bigotes (boxplots o box and whiskers) son una presentación visual que describe varias características importantes, al mismo tiempo, tales como la dispersión y simetría.<br>
Para su realización se representan los tres cuartiles y los valores mínimo y máximo de los datos, sobre un rectángulo, alineado horizontal o verticalmente.<br>
Link a la [documentación](https://matplotlib.org/3.3.1/api/_as_gen/matplotlib.pyplot.boxplot.html) de matplotlib.


![Boxplot](https://user-images.githubusercontent.com/43391630/97821719-70936980-1c81-11eb-8fa3-4ac05ecf07a2.png)


In [ ]:
plt.boxplot(df.length)

Vemos que la funcion `plt.boxplot` arroja como output un diccionario, en donde cada key corresponde a un elemento del gráfico. Vamos a utilizar este diccionario para modificar ciertas propiedades del grafico.

In [ ]:
# plt.figure(figsize=(10,5))
dic = plt.boxplot(x = [
                      df[df.smoker == 1].length,
                      df[df.smoker == 0].length
                      ],
                  meanline=True,
                  showmeans=True,
                  widths=[0.7,0.7],
                  labels=['Fumador','No Fumador']
                 )
[i.set_linewidth(0.3) for i in dic['boxes']] # Esto es una lista por comprension! 
#Si te cuesta entender que esta haciendo pensalo asi:
    # Para cada elemento en dic['boxes'] va a aplicar el metodo .set_linewidth (dado que YA SE que ambos seran objetos con este metodo)
dic['medians'][0].set_label('Mediana') # Como ambos objetos tienen media y mediana le colocare nombre a uno solo y luego ploteare la leyenda
dic['means'][0].set_label('Media')

plt.title('Largo del bebe al nacer')
plt.legend()
plt.show()

#### Subplots
`matplotlib` nos permite crear plots que contengan plots mas pequeños dentro, o mejor dicho subplots. 
Esto nos sera útil al momento de traducir metricas como las que vimos cuando usamos `pd.describe` de una manera gráfica para cada variable de interes.

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
plt.subplots(nrows=4,ncols=3)

Vemos que el output de `subplots` es una tupla con dos elementos una Figura y un array con Ejes (Axes). [Documentación](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplots.html)<br>
A modo breve, podemos decir que la Figura es el "marco" y los ejes los "elementos" de nuestro cuadro o imagen. 
Cada elemento tendra sus propios `atributos` y `metodos`. 
Sobre los ejes plotearemos nuestros gráficos individuales, en cada eje plotearemos un grafico puntual, epero como ya vimos tambien podemos superponer los graficos.<br> Usaremos la Figura solamente para modificar aspectos estéticos de la imagen como tal.

In [ ]:
fig, axs = plt.subplots(nrows=3,ncols=3)
axs[0,0].boxplot(df.length) # Ploteo nuestro histograma en el primer eje
axs[0,0].set_title('Largo al nacer') # Tambien puedo setear los mismo elementos que con un solo plot
axs[0,0].set_ylabel('Lenght')
fig.set_size_inches(10,8) # cambio el tamaño de TODA la figura
plt.show()

In [ ]:
vars_interesante = ['headcirumference', 'length', 'Birthweight', 'Gestation',
        'motherage', 'mheight', 'mppwt','mnocig', 'fheight']
fig, axs = plt.subplots(nrows=3,ncols=3)

for idx, ax in enumerate(axs.ravel()):
    ax.boxplot(df[vars_interesante[idx]])
    ax.set_title(vars_interesante[idx]) 
    ax.set_xticklabels('') # Saquemos los labels ya que es una sola variable
fig.set_size_inches(10,8)

A simple vista podemos ver que nuestro dataset esta bastante bien curado. Hay muy poco valores outliers (aquellos por fuera de este rango interquartil, o 95% de los valores). En caso de tener muchos outliers en un caso deberiamos inspeccionar a que se puede deber esto. Cada dataset es un mundo, y entre mejor sepamos como los datos fueron recolectados mejor podremos entender a que se puede deber estos outliers. 

In [ ]:
axs.ravel()

#### Barplot

Un diagrama de barras, también conocido como gráfico de barras o gráfico de columnas, es una forma de representar gráficamente un conjunto de datos o valores mediante barras rectangulares de longitud proporcional a los valores representados. Los gráficos de barras pueden ser usados para comparar cantidades de una variable en diferentes momentos o diferentes variables para el mismo momento. Las barras pueden orientarse horizontal y verticalmente.

Si bien `matplotlib` ofrece la posibilidad de generar estos gráficos, considero mas recomendable usar `Seaborn`. Esta librería nos ofrece funcionalidades muy buenas para poder hacer plots segmentando nuestras variables principales (x,y) por alguna variable secundaria mediante la opción `hue`.
[Seaborn (Documentación)](https://seaborn.pydata.org/)

En este caso vamos a usar un tipo de barplot específico denominado `countplot` el cual se utiliza para contar la cantidad de casos por categoría de variable

In [ ]:
import seaborn as sns # Importo la librería

In [ ]:
ax = sns.countplot(data = df,
                   x='smoker')

In [ ]:
ax = sns.catplot(data=df,
                 x='smoker',
                 kind='count')

Seaborn es incluso más cómodo al momento de plotear subplots. Seaborn acepta como argumento `ax` un objeto de tipo Axes.

In [ ]:
fig, axs = plt.subplots(1,3)
categoricas = ['smoker', 'mage35', 'LowBirthWeight']

for idx, ax in enumerate(axs.ravel()):
    sns.countplot(data = df,
                  x = categoricas[idx],
                  ax=ax
                 )
fig.set_size_inches(10,5)

### 5. Análisis bivariado

Hasta ahora hemos puesto enfasis en los graficos univariados, pero ya hemos visto como hemos incluido otras variables en nuestros gráficos (ej largo dividido por fumanod/no fumador). 
No solo nos interesa saber como se "ve" una variable particular, sino como interactua con otras variables de nuestro dataset. Esto nos va a permitir empezar a dilucidar ciertas hipotesis, problemas, etc.

In [ ]:
# Seaborn nos ofrece un comando simple en el cual vamos a poder plotear todos las variables de nuestro dataset
# contra todas las demas. Si bien puede ser útil veremos que cuando tenemos muchos datos esto puede ser confuso
sns.pairplot(df)

In [ ]:
sns.pairplot(df.loc[:,['Birthweight','headcirumference', 'length', 
                       'Gestation','mnocig', 'mheight', 'mppwt','smoker']],)
            #hue='smoker')

In [ ]:
sns.scatterplot(data=df, x='mppwt', y='Birthweight', hue='smoker')

En este dataset contamos con varias columnas. Cuando tenemos demasiada información puede ser confuso entender qué está pasando. En esos casos es bueno representar la información gráficamente. Vamos a crear una [matrix de correlacion](https://es.wikipedia.org/wiki/Matriz_de_correlaci%C3%B3n#:~:text=Estas%20variables%20independientes%20o%20explicativas,la%20relaci%C3%B3n%20entre%20cada%20pareja)

#### Correlation plot

In [ ]:
# Correlacion
# Pandas viene por defecto con una función que calcula la matriz por nosotros --> corr 
df.corr()

In [ ]:
# Vamos a usar seabron para plotear esta matriz
import seaborn as sbn # Libreria para plotear, mas linda que matplotlib y con graficos útiles
sbn.heatmap(df.corr())

 Baia baia, si bien ahora podemos ver toda la información al mismo tiempo, aún no es muy claro.  Vamos a hacer una matriz mas bonita y facil de entender usando numpy y seaborn

In [ ]:
mask = np.triu(np.ones_like(df.corr(), dtype=np.bool)) # vamos a quedarnos solo con el triangulo inferior de la matriz
# np.triu devuelve una matriz triangular, en este caso populada con booleans (True) para el triangulo inferior.

plt.figure(figsize = (10,10)) # creo una figura con un tamañ de 10*10
sbn.heatmap(df.corr(),
            mask=mask, #seaborn viene con la opcion de alimentar a nuestro plot con una mascara
            center=0,  #centramos el valor de correlacion 0 como el punto medio de nuestra barra
            cmap = 'RdBu',
            # Elegimos un mapa de colores mas intuitivo (https://seaborn.pydata.org/generated/seaborn.color_palette.html#seaborn.color_palette)
            square=True, 
            linewidths=.5,
            cbar_kws={"shrink": .7})
plt.title('Matriz de correlación')
plt.show()

**Esto se ve mucho mejor!**
Si observamos el grafico automáticamente se observan 3 lineas rojas:

`smoker` : Codifica si la madre fumó o no durante el embarazo (nominal)<br>
`mnocig` : Numero de cigarrillos fumados por la madre por día<br>
`lowbwt` : Bajo peso al nacer (nominal)<br>

Para este curso vamos a concentrarnos en una sola variable para hacer nuestros análisis. Utilizaremos una variable similar a `lowbwt ` pero expresada de una manera cuantitativa: `Birthweight`. Esta variable indica el peso del recien nacido en libras.

Dada nuestra matriz de correlación, podemos suponer que el peso de un recien nacido puede estar influenciado por el consumo de tabaco da la madre durante el embarazo.

 *Pequeña aclaración, si bien podemos hacer análisis inferencial sobre estos datos, esto no implica que se realizo un diseño experimental para poder corroborar causalidad entre estas variables.*

---

## 4. Introducción a la estadística inferencial

**Que veremos en esta unidad:**

- [Contraste de hipotesis][Modeling]
- Introduccion a [Statsmodels][Statsmodels]
- Test de normalidad de variables [Shapiro-Wilk][Shapiro-Wilk]
- [QQplots][QQplots]
- Distintos [datasets][Datasets] disponibles

[Modeling]:http://conceptosclaros.com/contraste-hipotesis/
[Statsmodels]:https://www.statsmodels.org/stable/index.html
[Shapiro-Wilk]:https://machinelearningmastery.com/a-gentle-introduction-to-normality-tests-in-python/
[QQplots]:https://www.geeksforgeeks.org/qqplot-quantile-quantile-plot-in-python/
[Datasets]:https://www.sheffield.ac.uk/mash/statistics/datasets

In [ ]:
# Importamos librerias que nos seran útiles 
import scipy.stats as stat  # Libreria con diversos test estadísticos
import seaborn as sbn  # Libreria para plotear, mas linda que matplotlib y con graficos útiles

### Distribution plot

In [ ]:
# Seaborn nos permite no solo plotear el histograma, sino tambien la distribucion de la variable
sbn.distplot(df.Birthweight,
             bins = 10,
             color = 'purple',
             hist_kws={'edgecolor':'k'})
plt.show()

In [ ]:
peso_fumador = df[df.smoker == 1].Birthweight # vamos a aislar nuestras variables dependiendo si la madre fumó o no durante el embarazo
peso_no_fumador = df[df.smoker == 0].Birthweight

In [ ]:
# Plots
fig, axs = plt.subplots(1,2,figsize = (10,5)) # Dado que tengo dos grupos vamos a plotearlos uno al lado del otro
# plt.subplots() nos va a devolver en este caso una figura y unos ejes, mas precisamente devolverá 2 ejes.
# los dos primeros numeros (1,2) significa 1 fila ,  2 columnas

sbn.distplot(peso_no_fumador,
             bins = 8,
             color = 'green',
             hist_kws={'edgecolor':'k'},
             label = 'No fumador',
             ax=axs[0])
axs[0].legend(bbox_to_anchor=(2.7,1)) # Modifico la ubicacion de la leyenda
axs[0].set_ylabel('Density') # Le pongo un nombre al eje y

sbn.distplot(peso_fumador,
             bins = 8,
             color = 'red',
             hist_kws={'edgecolor':'k'},
             label = 'Fumador',
             ax=axs[1])
axs[1].legend(bbox_to_anchor=(1.45,.9)) # Modifico la ubicacion de la leyenda
plt.suptitle('Distribucion de mis dos variables') # Titulo de toda la figura
plt.show()

### Graficos de cajas y bigotes ('Boxplot')

In [ ]:
fig = plt.boxplot([peso_no_fumador,peso_fumador],
            labels=['No fumador', 'Fumador'],
            patch_artist=True)

fig['boxes'][0].set(facecolor = 'green')
fig['boxes'][1].set(facecolor = 'red')
plt.ylabel('Peso al nacer (libras)')
plt.show()

In [ ]:
# Podemos usar Seaborn en lugar de lib. Observe las diferencias entre una libreria y otra
ax = sbn.boxplot(data = df, y = 'Birthweight', x = 'smoker',  hue='smoker', palette={0:'green', 1:'red'})
ax.set_xticklabels(['No fumador','Fumador'])
plt.show()

A primera vista hay una diferencia en el peso al nacer y el hecho de fumar o no. El primer paso antes de realizar cualquier tipo de test estadístico es corroborar los supuestos de los test que queremos emplear. En este caso, usaremos test paramétricos los cuales tienen diversos supuestos, siendo los principales la normalidad de nuestras variables y la igualdad de varianza

 Para mas información consultar el siguiente [link](https://www.scientific-european-federation-osteopaths.org/wp-content/uploads/2019/01/Estad%C3%ADstica-param%C3%A9trica.pdf)

 Vamos a plotear la distribución de nuestra variable `peso al nacer`, para ver si luce normalmente distribuída.

In [ ]:
sbn.distplot(peso_no_fumador,
             bins = 8,
             color = 'green',
             hist_kws={'edgecolor':'k'},
             label = 'No fumador',
             hist = False) 

sbn.distplot(peso_fumador,
             bins = 8,
             color = 'red',
             hist_kws={'edgecolor':'k'},
             label = 'Fumador',
             hist = False)
plt.legend()
plt.show()

Las distribuciones se ven normales, estando la distribucion para los `No fumadores` corrida a la derecha. Los valores para los `No fumadores` parecerían estar mas concentrado alrededor de la media. Esto nos daria una idea de la varianza de los datos. 
Para indagar más detalladamente sobre la normalidad de nuestros datos, podemos plotear un [QQ-plot](https://www.geeksforgeeks.org/qqplot-quantile-quantile-plot-in-python/)

### QQ plot

In [ ]:
import statsmodels.api as sm  # Esta libreria cuenta con diferentes pruebas estadisticas.

fig, axs = plt.subplots(1,2, figsize = (10,5))
_ = sm.qqplot(peso_fumador, line ='s', ax = axs[1], label = 'Fumador')  # Por que el _? porque la funcion sm.qqplot por defecto plotea el grafico
_ = sm.qqplot(peso_no_fumador, line ='s', ax = axs[0], label = 'No fumador')  # y como queremos plotearlos juntos no nos importa el output
axs[1].set_title('Fumador')
axs[0].set_title('No fumador')
plt.show()

Si bien los datos lucen normalmente distribuidos, podemos corroborar esto realizando un test de normalidad. Para eso usaremos el test de normalidad [Shapiro-Wilk](https://machinelearningmastery.com/a-gentle-introduction-to-normality-tests-in-python/)

In [ ]:
s, p = stat.shapiro(peso_fumador)
print('Fumadores', f'Shapiro Wilk = {s:.2f}',f'p-value = {p:.2f}', sep='\n')

In [ ]:
s, p = stat.shapiro(peso_no_fumador)
print('No fumadores', f'Shapiro Wilk = {s:.2f}',f'p-value = {p:.2f}', sep='\n')

Testeemos la homoceasticidad (o igualdad de varianzas) de las variables solo para estar seguros. Para eso usaremos el test de homoceasticidad de [Bartlett](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bartlett.html?highlight=bartlett#scipy.stats.bartlett)

In [ ]:
s, p = stat.bartlett(peso_fumador,peso_no_fumador)
print('Homoceasticidad de varianza',
      f'Bartlet (T) = {s:.2f}',
      f'p-value = {p:.2f}', sep = '\n')

### Test de Student 
Ralizamos un test de student para observar si hay o no diferencias entre las medias de la población de nuestras variables

In [ ]:
t,p,dg = sm.stats.ttest_ind(peso_fumador,peso_no_fumador)
# Esto se llama unpacking. Dado que la funcion devuelve tres valores yo puedo elegir guardarlo como una lista
# o puedo asignarlo a tres variables diferentes.

In [ ]:
print(f'Se rechaza la hipotesis nula (H0) de que las dos distribuciones son iguales.',
      f'Hay una diferencia estadísticamente significativa entre las medias (T={t:.2f} , p={p:.3f})',
      'Se puede afirmar que los niños recien nacidos de madres fumadores, pesan menos al nacer que los niños' \
      'de madres que no fumaron durante el embarazo',
      sep = '\n')

**Importante** A pesar de que podemos afirmar una diferencia entre las medias de estas poblaciónes no podemos afirmar causalidad debido a que este es un análisis retrospectivo. 

### Aproximación al modelado estadístico usando Python 

Si bien, el modelado estadístico en Python per se amerita un curso por si mismo, no quería terminar sin mostrar una breve aproximación. 
Si bien R es por defecto la primera opción cuando hablamos de modelados estadístico cláasico, librerías como Statsmodels nos ofrece los principales test estadísticos de una manera amigable. 
Para esta breve demostración queria utilizar nuesto ya conocido dataset y emplear una [Regresion líneal](https://www.statsmodels.org/stable/regression.html)

Ahora bien, si realizamos una regresión lineal usando `smoker` como factor, no va a ser diferente (o no deberia al menos!) del T-Test que realizamos anteriormente. 
Para recapitular, esta es la formula empleada en la regresión líneal:

$$ y = Xβ + μ , \text{donde}\, μ ∼ N(0,Σ)$$

En nuestro caso intentaremos predecir **y** (`Birthweight`), usando como covariables unicamente una sola variable: `smoker`. Por ende mas que una matriz, usaremos un vector.

In [ ]:
import statsmodels.api as sm # Importamos la libreria 
X = sm.add_constant(df[['smoker']]) # Definimos nuestra matriz de covariables X y le agregamos nuestro vector de coeficientes 𝛽 utilizando la función add_constant
y = df.Birthweight 
model = sm.OLS(y,X)
result = model.fit()

In [ ]:
#Si quieres ver como se ve esta matriz descomenta la línea de abajo
#X  

In [ ]:
print(result.summary())  # Printeamos nuestros resultado.

Nuevamente vemos que nuestro valor $T = -2.054$ y $p=0.047$. Esto nos permite nuevamente rechazar la $H_O$ de que los dos grupos tienen iguales medias.  

Y si estas acostumbrado a R y te gusta escribir las formulas puede sencillamente usar el modulo `formula`. <br>
Tambien es más cómodo para escribir interacciones entre variables. Para indagar mas acerca de esto consultar el siguiente [link](https://www.statsmodels.org/devel/example_formulas.html)<br>
Veamos un ejemplo

In [ ]:
from statsmodels.formula.api import ols  # Importo el modelo `ols` de otro modulo, en este caso el modulo `formula`
model_formula="Birthweight ~ smoker"   # Identica sintaxis que en R
r_model = ols(formula=model_formula, data = df).fit()
print(r_model.summary())

**Ambos resultados coinciden!!**

Veamos un poco mas de cerca que predijo nuestro modelo, para eso usaremos nuestras habilidades con matplotlib!


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sbn

plt.figure(figsize=(15,5)) # Establezco un tamaño grande para trabajar mas cómodo
plt.plot(result.predict(X)[result.predict(X) > 7], marker = 'd',markersize = 5, linewidth = 0, color = 'lightgreen') # El modelo solo predice dos valores, es decir, un valor para fumadores y otro para no fumadores
plt.plot(result.predict(X)[result.predict(X) < 7], marker = 'd',markersize = 5, linewidth = 0, color = 'tomato') # Puedes observar los diferentes valores printeando `result.predict(X)`
plt.ylim(df.Birthweight.min(),df.Birthweight.max()) # Seteo límites para que coincida con nuestro próximo gráfico
plt.show()

In [ ]:
plt.figure(figsize=(15,5))
plt.plot(result.predict(X)[result.predict(X) > 7], marker = 'd', markersize = 5, linewidth = 0, color = 'lightgreen')
plt.plot(result.predict(X)[result.predict(X) < 7], marker = 'd', markersize = 5, linewidth = 0, color = 'tomato') 
plt.plot(df[df.smoker == 1].Birthweight,  marker = '.', linewidth = 0, markersize = 10, color = 'red', label = 'Fumador') # Agreguemos nuestros valores ya conocidos para ver que tal le fue a nuestro modelo!
plt.plot(df[df.smoker == 0].Birthweight,  marker = '.', linewidth = 0, markersize = 10, color = 'green', label = 'No fumador')

plt.ylabel('Peso al nacer (en libras)')
plt.xlabel('N de observación')
plt.legend()
plt.show()

A simple vista no es muy sorprendente, pero recordemos que estamos usando una regresión para emular una simple comparacion entre grupos. 

Intentemos un modelo un poco más complejo que tenga en cuenta variables la altura de la madre, dado que estaa variable puede estar influenciando el peso del recien nacido.

In [ ]:
model_formula="Birthweight ~ smoker + mheight" 
model_complex = ols(formula=model_formula, data = df).fit()
print(model_complex.summary())

In [ ]:
from statsmodels.stats.anova import anova_lm # importamos un test para comparar ambos modelos, el inicial mas simple y nuestro modelo mas complejo
anova_lm(result,model_complex)

Si el lector lo deseá puede consular el siguiente [post](https://medium.com/@rrfd/f-tests-and-anovas-examples-with-the-iris-dataset-fe7caa3e21d0) explicando mas acerca de este F-Test.
En resumen, nuestro modelo más complejo es mejor para explicar la variabilidad de nuestra variable de interes.

Veamos que predijo

In [ ]:
plt.figure(figsize=(15,5))
plt.plot(model_complex.predict(df[['smoker','mheight']]), marker = 'd', markersize = 5, linewidth = 0, color = 'gray')
plt.plot(df[df.smoker == 1].Birthweight,  marker = '.', linewidth = 0, markersize = 10, color = 'red', label = 'Fumador')
plt.plot(df[df.smoker == 0].Birthweight,  marker = '.', linewidth = 0, markersize = 10, color = 'green', label = 'No fumador')

plt.ylabel('Peso al nacer (en libras)')
plt.xlabel('N de observación')
plt.legend()
plt.show()